export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_USER = "ADD_USER";
export const GET_USERS = "GET_USERS";
export const LOADING_USERS = "LOADING_USERS";

export const ADD_PATIENT = "ADD_PATIENT";
export const GET_PATIENTS = "GET_PATIENTS";
export const LOADING_PATIENTS = "LOADING_PATIENTS";

export const ADD_DRUG = "ADD_DRUG";
export const GET_DRUGS = "GET_DRUGS";
export const LOADING_DRUGS = "LOADING_DRUGS";

export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const GET_PRESCRIPTION = "GET_PRESCRIPTION";
export const GET_PRESCRIPTIONS = "GET_PRESCRIPTIONS";
export const LOADING_PRESCRIPTIONS = "LOADING_PRESCRIPTIONS";

export const ADD_DRUG_PRESCRIPTION = "ADD_DRUG_PRESCRIPTION";
export const DELETE_DRUG_PRESCRIPTION = "DELETE_DRUG_PRESCRIPTION";
